CREATE DATABASE IF NOT EXISTS CheapoDB;

CREATE TABLE IF NOT EXISTS User(
    id INT UNSIGNED NOT NULL PRIMARY KEY,
    firstname VARCHAR(20) DEFAULT NULL,
    lastname VARCHAR(20) DEFAULT NULL,
    usernmae VARCHAR(20) DEFAULT NULL,
    password VARCHAR(20) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS Message(
    id INT UNSIGNED NOT NULL PRIMARY KEY,
    recipient_id INT UNSIGNED NOT NULL,
    user_id  INT UNSIGNED NOT NULL,
    subject VARCHAR(20) DEFAULT NULL,
    body VARCHAR(400) DEFAULT NULL,
    date_sent DATE NOT NULL,
);

CREATE TABLE IF NOT EXISTS Messgae_read(
    id INT UNSIGNED NOT NULL PRIMARY KEY,
    message_id INT UNSIGNED NOT NULL,
    reader_id INT UNSIGNED NOT NULL,
    date DATE NOT NULL
);
